cameras:
- id: 0
  intrinsics:
    cx: 640.0
    cy: 360.0
    distortion: &id001
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    fx: 1000.0
    fy: 1000.0
  primary: true
  type: standard
- id: 1
  intrinsics:
    cx: 640.0
    cy: 360.0
    distortion: *id001
    fx: 1000.0
    fy: 1000.0
  primary: false
  type: standard
- id: 2
  intrinsics:
    cx: 640.0
    cy: 360.0
    distortion: *id001
    fx: 1000.0
    fy: 1000.0
  primary: false
  type: standard
